# Dependencies
markdown:         redcarpet
highlighter:      null

# Permalinks
permalink:        pretty

# Setup
title:            reader to writer
tagline:          '{outside my window, dreaming}'
description:      'because a year from now, you''ll wish you had started today'
url:              http://readertowriter.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'me'
  url:            https://twitter.com/readertowriter

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
